### ISSUE TITLE
Folder context menu

### ISSUE THREAD

**Issue by pyhoon** [Red-Error404/Emerald#1]
This project doesn't work properly. When I run the project, the windows and font do not render properly. It also created an "open with" context menu when right click on any folder which is annoying. I tried to remove using regedit but it still exist. At the end I use System restore to restore my Windows settings.

**Comment by buger404** [comment]
**I'm very sorry about that** . Emerald always create a Chinese font named "微软雅黑"(Microsoft YaHei) so that it can't work properly on your computer , you can try to edit the paramarray of `MakeFont` .
And about the content menu , you can press Ctrl+R , type `control` and find 'Emerald' then uninstall .
If the question still doesn't solve , try to delete :
```vbs
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\shell\emerald\icon"
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\shell\emerald\version"
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\shell\emerald\command\"
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\shell\emerald\"
    
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\Background\shell\emerald\icon"
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\Background\shell\emerald\command\"
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\Background\shell\emerald\"
    
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\shell\emeraldp\icon"
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\shell\emeraldp\command\"
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\shell\emeraldp\"
    
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\Background\shell\emeraldp\icon"
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\Background\shell\emeraldp\command\"
    WSHShell.RegDelete "HKEY_CLASSES_ROOT\Directory\Background\shell\emeraldp\"
```
Finally , thanks for your supporting !
>If you can't understand my words , please call me .

**Comment by pyhoon** [comment]
Thanks for replying. I have solved the issue by System restore. I hope this guide will benefit someone else or you can put it inside the Wiki.
